# The specific values for the microservice. Whatever is defined here will...
# ...overwrite values.yaml. Anything not defined, will just take the value defined in values.yaml
appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"

servicePort: 9555
serviceType: ClusterIP
