# The specific values for the microservice. Whatever is defined here will...
# ...overwrite values.yaml. Anything not defined, will just take the value defined in values.yaml
appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 7070
containerEnvVars:
- name: PORT
  value: "7070"
- name: REDIS_ADDR
  value: "redis-cart:6379"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7070
serviceType: ClusterIP
