# The specific values for the microservice emailservice. Whatever is defined here will...
# ...overwrite values.yaml. Anything not defined, will just take the value defined in values.yaml
appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"

servicePort: 5000
serviceType: ClusterIP
